workflows:
  android-build:
    name: Compilar APK EdgeOS
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      groups:
        - android_credentials
      vars:
        PUBLIC_URL: "https://pollinations.ai"
      node: latest
    scripts:
      - name: Instalar Buildozer e Dependencias
        script: |
          pip install buildozer cython virtualenv kivy reportlab urllib3
      - name: Gerar APK em Silencio
        script: |
          yes | buildozer -v android debug
    artifacts:
      - bin/*.apk
