name: Gerador de APK EdgeOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar Dependencias do Sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y ccache git libffi-dev libssl-dev autoconf automake libtool pkg-config zlib1g-dev python3-pip python3-setuptools python3-dev overlayroot openjdk-17-jdk unzip zip

    - name: Instalar Cython e Buildozer
      run: |
        pip install --upgrade pip
        pip install Cython==0.29.36 buildozer

    - name: Compilar APK em Silencio Absoluto
      run: |
        buildozer android debug

    - name: Liberar Download do APK Pronto
      uses: actions/upload-artifact@v4
      with:
        name: EdgeOS-Solutions-v3.1
        path: bin/*.apk
